### ISSUE TITLE
spr_bus_ack_o reset issue

### ISSUE THREAD

**Issue by Harshitha172000** [openrisc/mor1kx#127]
This issue is applicable to the mor1kx_icache module. After resetting, the state moves to IDLE but spr_bus_ack_o can be high if spr strobe/write signals stays high during reset. This is possible as spr stb/we signals are not reset in the ctrl module.

Assertion Failed:
```
          always @(posedge clk)
               if ($past(rst) && f_past_valid)
                  assert (!spr_bus_ack_ic_i);
```
Trace showing issue:

![image](https://user-images.githubusercontent.com/59602295/124925413-086c0300-e01a-11eb-8dba-0f704c53dc2f.png)

**Comment by stffrdhrn** [comment]
I posted a fix for this does it also fix formal?

**Comment by Harshitha172000** [comment]
No, now I see this trace.  With the reset, the state switches from INVALIDATE to IDLE and keeps spr_bus_ack_o high.

![image](https://user-images.githubusercontent.com/59602295/125103226-c4502f80-e0f9-11eb-8100-06869bdd5d00.png)

**Comment by stffrdhrn** [comment]
OK, it doesn't cater for the case when `spr_bus_ack_o` is high to start with.

**Comment by stffrdhrn** [comment]
I pushed another update, how does it look now?

**Comment by Harshitha172000** [comment]
It passes the test, the issue is resolved.
