### ISSUE TITLE
Reset Issues

### ISSUE THREAD

**Issue by TAS67** [openrisc/mor1kx#53]
** Conditional Loading without a reset**
In mor1kx_lsu_cappuccino there is a reset missing, when FEATURE_STORE_BUFFER==NONE.

The register store_buffer_full_r does not have a reset, and it is conditionally loaded, but the condition cannot be met unless the regiser contains a valid value. 

``
reg store_buffer_full_r;
   always @(posedge clk)
    if (store_buffer_write)
       store_buffer_full_r <= 1;
     else if (write_done)
       store_buffer_full_r <= 0;
``

In simulation, store_buffer_full_r is initialised to 1'bx and as a result store_buffer_full is 1'bx, and this prevents writes from completing, and as a result simulation hangs.

There other registers in the design which have a similar conditional loading feature and no reset. They do not cause SIM to hang, but it is not clear if they are safe.

**Mixed Sync and Async Resets**
The majority of the registers in mor1kx which have a reset use the `OR_ASYNC_RST macro to give the option of the reset being asynchronous, but some registers, such as the "state" register in mor1kx_lsu_cappuccino treat the reset as unconditionally synchronous. This means someone who wants to use asynchronous resets my not achieve a clean reset unless they start the clock whilst the reset is active.

**Comment by stffrdhrn** [comment]
Fixed in merged pull requests,  tests seem to show its working too.  Closing
