### ISSUE TITLE
GLIP FX3 & Debugging at the same time?

### ISSUE THREAD

**Issue by densoaber** [openrisc/mor1kx#78]
I´m wondering if GLIP usage with FX3 backend and GDB debugging is supported anyhow ?
Or is a colaboration of JTAG and FX3 backend possible ?

**Comment by stffrdhrn** [comment]
We do do GDB debugging with openocd using jtag.  See the tutorial:
https://github.com/openrisc/tutorials/blob/master/docs/Debugging.md

**Comment by stffrdhrn** [comment]
Note, this is using the fusesoc de0_nano soc, which uses adv_debug_sys
https://github.com/olofk/de0_nano/blob/master/de0_nano-1.1.core

**Comment by stffrdhrn** [comment]
I am closing, let me know if you have more questions of got this sorted out.
