### ISSUE TITLE
Problem about putting mor1kx into Xilinx FPGA

### ISSUE THREAD

**Issue by hyf6661669** [openrisc/mor1kx#79]
Hello, I want to put mor1kx into my Xilinx Xc7k325t-2 FPGA for hardware simulation. Have you tested the max operating frequency that mor1kx can achieve on Xilinx 7 series FPGA? 

Thanks!

**Comment by stffrdhrn** [comment]
Hello, I haven't tested.  But on other FPGAs (cyclone iv) I have reached 100mhz.  I didn't try to push it though.

**Comment by hyf6661669** [comment]
@stffrdhrn  Thanks！
