### ISSUE TITLE
Replace custom image by providing LibreCores CI Image 

### ISSUE THREAD

**Issue by Nancy-Chauhan** [openrisc/mor1kx#81]
This issue is in direction of Setting up Demo CI Flow for mor1kx Project. Currently mor1kx constantly evolving code is verified by [Travis Continous Integration](https://github.com/openrisc/mor1kx/blob/master/.travis.yml). One of the first aim of GSoC 2019 project is to use Librecores CI for Continous Integration of mor1kx. [Librecores CI](https://www.librecores.org/static/librecores-ci) is an approach/service to provide continuous integration to hardware projects hosted on [Librecores](https://www.librecores.org/static/) to improve user experience and reliability.

**Goal :** This will create shared tooling of [Librecores CI image](https://github.com/librecores/docker-images/tree/master/librecores-ci) with mor1kx project 
**Implementation :** With reference to issue https://github.com/librecores/docker-images/issues/10 , it will be possible to replace custom dockerfile image used in mor1kx project https://github.com/openrisc/mor1kx/tree/master/.travis with Librecores CI image . Further Jenkinsfile can be created for refactoring of existing travis CI 

**_Project Link_**: https://github.com/librecores/librecores-ci/ 

 
 

CC @oleg-nenashev @wallento @stffrdhrn
[_Link to doc proposal_ ](https://docs.google.com/document/d/1d0mIrLpU80IqB5oe4CvUz5H3bMR84tg0P99doWrovek/edit)

**Comment by oleg-nenashev** [comment]
Please add description and link to other tasks in your GSoC project scope
