### ISSUE TITLE
Add @librecores-ci-bot to the repository

### ISSUE THREAD

**Issue by oleg-nenashev** [openrisc/mor1kx#86]
@Nancy-Chauhan is working on enabling LibreCores CI runs for this repository (e.g. see #84 and #85 ). In order to make it a part of the pull request builder, we need @librecores-ci-bot to be added to the repository with WRITE permissions so that it can post build results.

@stffrdhrn would it be possible to do so?

**Comment by stffrdhrn** [comment]
Sure

**Comment by stffrdhrn** [comment]
I have sent an invite

**Comment by oleg-nenashev** [comment]
done
